/**
 * Dump a SQLite-compatible connection to a portable .sql script.
 */

import type { Connection, Row } from "../core/database.js";

function sqlLiteral(value: unknown): string {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number" && Number.isFinite(value)) return String(value);
  if (typeof value === "bigint") return String(value);
  if (typeof value === "boolean") return value ? "1" : "0";
  if (value instanceof Uint8Array) {
    const hex = Array.from(value, (b) => b.toString(16).padStart(2, "0")).join("");
    return `X'${hex}'`;
  }
  const str = String(value);
  return `'${str.replace(/'/g, "''")}'`;
}

function quoteIdent(name: string): string {
  return `"${name.replace(/"/g, '""')}"`;
}

export async function dumpConnection(
  conn: Connection,
  header: string,
  opts: { generatedBy?: string } = {},
): Promise<string> {
  const by = opts.generatedBy ?? "Keel";
  const lines: string[] = [
    `-- ${header}`,
    `-- Generated by ${by} at ${new Date().toISOString()}`,
    "PRAGMA foreign_keys=OFF;",
    "BEGIN TRANSACTION;",
    "",
  ];

  const objects = await conn.select(
    "SELECT type, name, sql FROM sqlite_master WHERE name NOT LIKE 'sqlite_%' AND sql IS NOT NULL ORDER BY CASE type WHEN 'table' THEN 0 WHEN 'index' THEN 1 ELSE 2 END, name",
    [],
  );

  const tables = objects.filter((o) => o.type === "table" && typeof o.name === "string");

  for (const table of tables) {
    const name = String(table.name);
    if (table.sql) {
      lines.push(`DROP TABLE IF EXISTS ${quoteIdent(name)};`);
      lines.push(`${String(table.sql)};`);
      lines.push("");
    }

    const rows = await conn.select(`SELECT * FROM ${quoteIdent(name)}`, []);
    if (rows.length === 0) continue;

    const columns = Object.keys(rows[0] as Row);
    for (const row of rows) {
      const values = columns.map((col) => sqlLiteral((row as Row)[col]));
      lines.push(
        `INSERT INTO ${quoteIdent(name)} (${columns.map(quoteIdent).join(", ")}) VALUES (${values.join(", ")});`,
      );
    }
    lines.push("");
  }

  const indexes = objects.filter((o) => o.type === "index" && o.sql);
  for (const index of indexes) {
    lines.push(`${String(index.sql)};`);
  }

  lines.push("COMMIT;");
  lines.push("");
  return lines.join("\n");
}
